### ISSUE TITLE
first run of make rel fails

### ISSUE THREAD

**Issue by monkeydom** [jlouis/etorrent#102]
rebar generate
==> rel (generate)
ERROR: Unexpected error: {'EXIT',
                             {function_clause,
                                 [{mustache,escape,[true,[]]},
                                  {erl_eval,do_apply,5},
                                  {erl_eval,expr,5},
                                  {erl_eval,expr,5},
                                  {mustache,render,3},
                                  {rebar_reltool,execute_overlay,4},
                                  {rebar_reltool,generate,2},
                                  {rebar_core,run_modules,4}]}}
make: **\* [rel/etorrent] Error 1

**Comment by ghost** [comment]
Updating your rebar install will solve this problem:

See:  https://github.com/jlouis/etorrent/issues/closed#issue/67

And : https://github.com/basho/rebar

vielen dank

**Comment by monkeydom** [comment]
ah thanks. thought i got the most recent version from the official looking blog post at: http://alancastro.org/2010/05/01/erlang-application-management-with-rebar.html - has the project moved to git? distributed versioning seems to lack a notion of what is master/mainline :)

**Comment by jlouis** [comment]
Yeah, rebar is on github now, https://github.com/basho/rebar

The version I am using at the moment is:

rebar version: 2 date: 20110310_155239 vcs: git 2e1b4da

If this fixes your trouble, please get back to me, so I can kill this issue :)

**Comment by monkeydom** [comment]
yes it fixes it. please do kill! ;9

**Comment by jlouis** [comment]
Closed.
