### ISSUE TITLE
More sensible default locations for the spool files & auto directory creation

### ISSUE THREAD

**Issue by jameschurchman** [jlouis/etorrent#113]
Spool file, database tables etc.. locations are current set to var/local . This can be problematic and cause etorrent to crash / fail to start if the user does not have the correct permissions to write in these directories

Better would be something like ~/.etorrent

Also etorrent seems not to generate the directories referred to if they do not already exist. It seems to fail to start. It should either display a warning that they don't exist, prompt the user that they don't and ask to create them for the user, or just make them directly if they do not.

**Comment by jlouis** [comment]
Some time ago, this suggestion was sent into 'master'. We now refer to an example where it is clear that the data directory lives under a user, rather than under /var/spool in general.
