### ISSUE TITLE
make rel fail, due module name conflicts

### ISSUE THREAD

**Issue by baryluk** [jlouis/etorrent#115]
Strange, but rebar or some general OTP application structure
have problem.

```
rebar generate
==> rel (generate)
{"init terminating in do_boot","Module array potentially included by two different applications: stdlib and wings."}
```

In fact yes, application wings have module array, which "overrides" stdlib's one (i guess it is have
some performance hacks there). However I do not see why etorrent is even looking into wings application.
It is not referenced directly or indirectly by any of apps in ettorrent, so it shouldn't be copied
into rel.

Any ideas (beside removing wings application from system).

Maybe be a rebar error.

Thanks.

**Comment by baryluk** [comment]
I notified wings maintainer, to remove this module, and merge it into upstream stdlib. Howerer still wonder why rebar makes a problem here.

**Comment by jlouis** [comment]
It may be a problem with wings, with reltool or with rebar. The problem is if it tries to package the wrong array module in there. It may be what goes wrong and then all kinds of trouble arrives.

**Comment by baryluk** [comment]
Ok Will ask rebar folks. Anyway, maintainer of wings, already promised me it will remove this module in near future.
