### ISSUE TITLE
make rel :: missing application directory

### ISSUE THREAD

**Issue by motiejus** [jlouis/etorrent#135]
I didn't check this in great detail yet, but just to let you know:

<pre>rebar version: 2 date: 20120429_105519 vcs: git dc472bd
Erlang R15B01 (erts-5.9.1) [source] [smp:2:2] [async-threads:0] [kernel-poll:false]

$ make rel
rebar compile
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/gproc'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/edown'
==> edown (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/edown'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/gen_leader'
==> gen_leader (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/gen_leader'
==> gproc (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/gproc'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/lager'
==> lager (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/lager'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/cowboy'
==> cowboy (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/cowboy'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/lhttpc'
==> lhttpc (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/lhttpc'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/mimetypes'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/proper'
==> proper (compile)
make[1]: Entering directory `/home/motiejus/code/stuff/etorrent/deps/proper'
make[1]: `include/compile_flags.hrl' is up to date.
make[1]: Leaving directory `/home/motiejus/code/stuff/etorrent/deps/proper'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/proper'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/proper_stdlib'
==> proper_stdlib (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/proper_stdlib'
==> mimetypes (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/mimetypes'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/meck'
==> meck (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/meck'
==> Entering directory `/home/motiejus/code/stuff/etorrent/rel'
==> rel (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/rel'
==> Entering directory `/home/motiejus/code/stuff/etorrent/apps/etorrent'
==> etorrent (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/apps/etorrent'
==> Entering directory `/home/motiejus/code/stuff/etorrent/apps/rlimit'
==> rlimit (compile)
==> Leaving directory `/home/motiejus/code/stuff/etorrent/apps/rlimit'
==> etorrent (compile)
rebar generate
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/gproc'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/edown'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/edown'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/gen_leader'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/gen_leader'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/gproc'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/lager'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/lager'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/cowboy'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/cowboy'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/lhttpc'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/lhttpc'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/mimetypes'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/proper'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/proper'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/proper_stdlib'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/proper_stdlib'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/mimetypes'
==> Entering directory `/home/motiejus/code/stuff/etorrent/deps/meck'
==> Leaving directory `/home/motiejus/code/stuff/etorrent/deps/meck'
==> Entering directory `/home/motiejus/code/stuff/etorrent/rel'
==> rel (generate)
ERROR: generate failed while processing /home/motiejus/code/stuff/etorrent/rel: {'EXIT',{{badmatch,{error,"riak_err: : Missing application directory."}},
         [{rebar_reltool,generate,2,[]},
          {rebar_core,run_modules,4,[]},
          {rebar_core,execute,5,[]},
          {rebar_core,process_dir0,6,[]},
          {rebar_core,process_dir,4,[]},
          {rebar_core,process_each,5,[]},
          {rebar_core,process_dir0,6,[]},
          {rebar_core,process_dir,4,[]}]}}
make: *** [rel/etorrent] Error 1</pre>

**Comment by jlouis** [comment]
The reason for the error is here:

https://github.com/jlouis/etorrent/blob/master/rel/reltool.config#L44

**Comment by jlouis** [comment]
I think I got this one fixed. Reltool still needs some care to become really good, but I've restructured stuff in and around releases for this thing.

**Comment by jlouis** [comment]
This should be fixed by now. There are other problems in the code base, but this particular one is not.
