### ISSUE TITLE
Rip out the cascadae dependency

### ISSUE THREAD

**Issue by jlouis** [jlouis/etorrent#142]
Rather than having etorrent_core depend on the webui's we shoul make etorrent_core oblivious to these and then use a release which can enable the webui's next to the core application. That way, we can split apart the core as a library from everything else.

**Comment by edescourtis** [comment]
I am interested in helping out if you don't mind me asking you a bunch of questions.

**Comment by jlouis** [comment]
Fire! The main problem is that the dependencies are the wrong way round. core should not depend on cascadae, but cascadae should depend on core. So everything with cascadae should be removed out of the core and then the core should be extended so cascadae can call into it.

**Comment by edescourtis** [comment]
Understood

**Comment by jlouis** [comment]
That is the basic problem. Another slight problem is that the code could use some help. There are many things I would like to do to it, but I am pressed for time, so I can't work full-time on it.

**Comment by edescourtis** [comment]
We can probably work something out. I can't work full-time on it either but together we might be able to do something about it.

**Comment by jlouis** [comment]
This should now be fixed.

**Comment by edescourtis** [comment]
Thank you! Sorry I didn't have time to do it I had many other things come up!
