### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by wstannl** [jlouis/etorrent#144]
I have tried to build etorrent but during "make compile" it goes into a "loop" and crashes. Not sure what to do about this.
Details:
FreeBSD 9.1
Erlang R15B03 (erts-5.9.3.1) [source] [smp:2:2] [async-threads:0] [kernel-poll:false]
rebar 2.0.0 R15B03 20130326_100154 No VCS info available.
commit b8c9f176ee7b7917b180d5fd3e0a7d43f352f376

==> Entering directory `/usr/home/wstan/etorrent/deps/etorrent_core'
==> Entering directory`/usr/home/wstan/etorrent/deps/cascadae'
==> Entering directory `/usr/home/wstan/etorrent/deps/etorrent_core'
==> Entering directory`/usr/home/wstan/etorrent/deps/cascadae'
==> Entering directory `/usr/home/wstan/etorrent/deps/etorrent_core'

**Comment by jlouis** [comment]
This has been fixed and cascadae is not a dependency anymore.
