### ISSUE TITLE
Implement DHT (BEP 5) in etorrent.

### ISSUE THREAD

**Issue by jlouis** [jlouis/etorrent#38]
Some DHT code is already there by klaar, so we are already partway to the goal.

**Comment by ghost** [comment]
I finally got some time to implement the routing table for the DHT node. The code is available at: http://github.com/klaar/etorrent/tree/bep-5

I have, and am, running a node to test it against other DHT implementations using that code.

#### AFAIK the TODO list is

```
 *  Persistent node-id and routing table
 *  Automatic bootstrapping of the routing table
 *  Actually refresh buckets with too many inactive nodes
 *  Adding a supervisor for the two servers
 *  Implementing a tracker "backend" (handle incoming announces and get_peers)
 *  Implementing a DHT tracker "client" (send announce and get_peers)
 *  edoc comments for the public API
 *  function specifications for dialyzer
 * support for dht options in config file
```

I might have missed an item there, but it should be pretty close.

**Comment by ghost** [comment]
Since the previous comment the following has been resolved:

```
* Persistent node-id and routing table
*  Implementing a tracker "backend" (handle incoming announces and get_peers)
```

**Comment by jlouis** [comment]
This is done, isn't it?

**Comment by ghost** [comment]
Yup, it works.

**Comment by jlouis** [comment]
Ok, done then!
