### ISSUE TITLE
Handle overload situations and SASL

### ISSUE THREAD

**Issue by jlouis** [jlouis/etorrent#54]
When we have a process dying with a 16K payload in hand, things go bad if there are too many of them. You quickly see 2G of memory used or worse. I and klaar have been looking at ways to make this better.
- We see the problems due to the fact that we timeout in gen_server:calls. We should probably just wait for infinity on a message to come back to us in most of the cases.
- The "last message in" only gets printed if we are trapping exits. Many of the exit traps can probably be removed since ports clean up themselves when their controlling process disappears anyway. That is, we let the other end clean up rather than us - and follow the Erlang-way in the process. A dying process should from the outset not clean up for itself.
- We could look into fixing SASL so it can cope with large messages. Basically, we could add some size protection to SASL which could be set as optional values in the configuration file. We could also look into fixing log_mf's error when a too big message gets passed to it.
  - We could research into creating a new error_logger which can cope better with large messages.

**Comment by ghost** [comment]
Reducing the amount of processes trapping exits is the low hanging fruit. That would ensure that, if not note, fewer "Last message in" entries are printed.

Installing custom event handlers in error_logger would be pretty straight forward,  the event handlers and module doing the formatting are relatively small. The difficult part is convincing myself that it won't have any nasty consequences.

The best solution is probably to both reduce the number of processes trapping exits, which is a good thing no matter what, and to install event_handlers that avoids formatting error messages that are known to include payloads.

**Comment by jlouis** [comment]
Basho's riak_err is what we need to incorporate into the code base to fix this problem.

**Comment by jlouis** [comment]
I have a branch for this...

**Comment by jlouis** [comment]
Merged to master.
