### ISSUE TITLE
Add UPnP support

### ISSUE THREAD

**Issue by jlouis** [jlouis/etorrent#6]
Add UPnP support to the client.

**Comment by edwardw** [comment]
I assume we are mainly interested in adding port forwarding to UPnP aware router.

After browsing UPnP documents, it appears to me to roughly counsist of three steps:
1. Discover UPnP-aware devices according to UPnP Device Architecture 1.0 document section 1 by sending certain udp message to multicast group 239.255.255.250:1900.
2. Response from UPnP-aware device will have a description url according to UPnP Device Architecture 1.0 document section 2. Talk to this url using standard http and device will return a detailed description of itself in xml format.
3. In returned description, we are interested in service type WANIPConnection or WANPPPConnection, which can carry on action AddPortMapping according to Internet Gateway Device (IGD) V 1.0 document. Talk to its control url to add port mapping we want.

**Comment by jlouis** [comment]
I agree with your research. It also sounds like a good plan for implementing the stuff, so go for it I'd say! xmerl is the module for doing xml parsing and it is in its own library it seems so it will have to be included in the release reltool.config file. There is an xpath in there as well, so digging inside the XML structure should not be too hard.

**Comment by jlouis** [comment]
http://en.wikipedia.org/wiki/NAT_Port_Mapping_Protocol is an alternative to uPnP which may or may not have been more successful

**Comment by edwardw** [comment]
uPnP specification is quite cumbersome to work with ;-) NAT PMP seems to be much more elegant. A classic Apple touch?

**Comment by jlouis** [comment]
It is far more permeating in my opinion than just Apple. It is the rule that the simple protocol that is adequate often wins over the complex protocol by simple virtue of being the path of least resistance.

Some of these very old issues are worth researching a bit before implementing as the state of the art might have changed in between.

**Comment by edwardw** [comment]
I agree. And simplicity is probably the hardest to achieve.

My preliminary UPnP implementation begins to work at last! It already did several hours ago but my tests said not. Until I realize that tests always fail unless there's someone actually listens on the port UPnP opens...

**Comment by edwardw** [comment]
Pull request sent.

**Comment by jlouis** [comment]
Done, pulled to master.
