### ISSUE TITLE
Do a state-passing audit on the code.

### ISSUE THREAD

**Issue by jlouis** [jlouis/etorrent#66]
"The code should flow like a State Monad".

That is, we should not be passing around state to helper functions which then return `{noreply, NewState}`. It is confusing to read. Fix by going through the code and untangling this mess.

**Comment by edwardw** [comment]
One example would be etorrent_peer_recv:next_msg/1. It reads:
    next_msg(#state { mode = transition } = S) ->
        {noreply, S};
    next_msg(#state { mode = fast } = S) ->
        {noreply, S};
    next_msg(#state { mode = slow } = S) ->
        {noreply, S, 0};
    next_msg(#state { mode = fast_setup } = S) ->
        {noreply, S, 0}.

And it will be called like this:
    handle_info(timeout, S) ->
        ....
        {error, etimedout} -> next_msg(S)

If we re-write it to something like:
    next_msg(#state { mode = slow } = S) ->
        {S, 0};
then:
    handle_info(timeout, S) ->
        ....
        {error, etimedout} -> {noreply, next_msg(S)}

Do I get the intention of this issue report right? If so, I'd like to take care of this one.

**Comment by jlouis** [comment]
Indeed yes! The idea is to handle the state at the top-level _as if_ it were a state monad and not pass around the state in subcomputations if possible. It is probably going to be much easier to read the code with your proposed transformation applied, so go ahead!

**Comment by edwardw** [comment]
I encountered one obstacle. Basically I need to 'flatten' a tuple, such as `{A, B, {C, D}}` -> `{A, B, C, D}`. Of course it should be generic enough. This is definitely a Monad! But I didn't figure out how to do that, yet.

Any idea?

**Comment by jlouis** [comment]
I am a bit vary of trying to make a generic flattener of tuples. You can of course try some combination of `list_to_tuple` and recursion but chances are it will work too well and make every tuple into a list :) I'd rather handle each case separately. Where is it this problem occurs?

**Comment by edwardw** [comment]
In my proposed refactor, I suggested to re-write `next_msg/1` as:
    next_msg(#state { mode = slow } = S) ->
        {S, 0};
Then in caller:
    handle_info(timeout, S) ->
        ....
        {error, etimedout} -> {noreply, next_msg(S)}
It seems to be a straightforward transformation, but actually quite subtle. What we get after this refactor is:
    {error, etimedout} -> {noreply, {NS, 0}}
not:
    {error, etimedout} -> {noreply, NS, 0}

See? So I thought what I needed was some flattener of tuples. But as you said, record `S` is itself a tuple, which will be flattened too. So even if I can come up with a smart flattener, it won't work either.

Of course, I can use `list` instead of `tuple`. E.g.,
    next_msg(#state { mode = slow } = S) ->
        [S, 0];
and then:
    handle_info(timeout, S) ->
        ....
        {error, etimedout} -> list_to_tuple(lists:append([noreply], next_msg(S)))
But this is way too ugly and far more difficult to read. I suspect this is why you implemented `next_msg/1` as it is in the first place ;-)

Is there any other way to refactor this snippet of code other than, say, inlining and eliminating function `next_msg/1` alltogether?

**Comment by edwardw** [comment]
As a side note, I googled a little bit. It seems people do have similar questions, for languages like scala, haskell, lisp and python. Some links:
- http://scala-programming-language.1934581.n4.nabble.com/flatten-nested-tuples-td1956168.html
- http://bbs.prog365.com/other-programming-languages-haskell-lists-of-tuples-to-list-16694-1-1.html
- http://stackoverflow.com/questions/2488228/disadvantage-of-unlifted-type-products

And Erlang efficience guide says `lists:flatten/1` is expensive:
- [Deep and flat lists](http://www.erlang.org/doc/efficiency_guide/listHandling.html#id64617)

**Comment by jlouis** [comment]
There is another way to rewrite the code, which perhaps is more in alignment with what I had in mind:

```
next_msg(#state { mode = transition } = S) ->
   {noreply, S};
```

is changed to

```
next_msg(Mode) ->
   case Mode of
      transition -> {Mode, infinity}
```

and is called as:

```
handle_info(timeout, S) ->
....
{error, etimedout} -> 
   {NewMode, Timeout} = next_msg(S#state.mode),
   {noreply, S#state { mode = NewMode }, Timeout}
```

This has the effect of turning `next_msg/1` into a function with no knowledge of the #state{} tuple. Rather it is a state transformer of type `next_msg ( mode() ) -> { mode() , timeout() }`. It could then also be renamed into something which reflects its new purpose.

As for the flattening of tuples, it is usually not something you want to do in in Erlang, nor Haskell. Personally, I would just hoist it like in the above code and not worry about automating it too much. Since there are 3 calls to `next_msg/1` you might want to look into merging the code path so to limit the hoisting. I think that part of the code can be merged into fewer cases, one for stopping, one for proceeding:

```
Proceed = case gen_tcp:recv(...) of
  {ok, Packet} -> handle_packet(Packet), true;
  {error, closed} -> false;
  {error, timeout} -> true;
  ...
end,
case Proceed of
  true -> {NewMode, Timeout} = next_msg(S#state.mode),
             {noreply, S#state { mode = NewMode }, Timeout};
  false -> {stop, normal, S}
end;
...
```

**Comment by edwardw** [comment]
Patch for module `etorrent_peer_recv` was sent. And spotted another candidate `etorrent_peer_send`. Its patch may follow.

**Comment by edwardw** [comment]
`etorrent_peer_send` seems okay.

**Comment by jlouis** [comment]
If you peer around, I am sure there are more modules which needs some help like this. `etorrent_peer_control` is probably a candidate. I've been working a bit on `etorrent_tracker_communication` myself. But I think there are more modules needing help than these.

**Comment by jlouis** [comment]
I close this one for v1.3. We can always reopen it but I think the internal state passing has progressed some.
