### ISSUE TITLE
Negative number of Seeders

### ISSUE THREAD

**Issue by hce** [jlouis/etorrent#69]
When downloading this torrent: http://cdimage.debian.org/debian-cd/5.0.7/amd64/bt-dvd/debian-507-amd64-DVD-4.iso.torrent I saw -10 seeders (negative number) listed in the webui.

**Comment by jlouis** [comment]
I tried to reproduce this one, and grab the output from the tracker. But the tracker did respond with all positive values that got reflected correctly. Can you reproduce it reliably?

**Comment by hce** [comment]
No, unfortunately I cannot. The negative value has disappeared in my torrent listing, too. I've seen it three times so far, -10 in every case, each time a debian torrent...

**Comment by jlouis** [comment]
If it reoccurs, here is what to do:
1. Install the `eper` suite with redbug.
2. Stop the currently running etorrent session, remove all .torrent files from it
3. Build a remote node for query
   
   ```
   erl -name 'rb@127.0.0.1' -remsh 'etorrent@127.0.0.1' -setcookie etorrent
   ```
4.  Redbug the response handler from the tracker
   
   ```
   redbug:start("etorrent_tracker_communication:handle_tracker_response/4",
                     [{time, 60000}]).
   ```
5. Add the torrent.
6. See if the tracker response has negative values.

Of course this narrowing won't work if it is even more flaky. I could add a guard on the counts perhaps as an alternative.

**Comment by jlouis** [comment]
This one is too old that I care for it anymore. The code in and around that base has been changed a lot, so I don't expect the problem to be the same in any case. Closing.
