### ISSUE TITLE
Implement mldonkey gui protocol

### ISSUE THREAD

**Issue by edwardw** [jlouis/etorrent#94]
http://mldonkey.sourceforge.net/GuiProtocol

Mldonkey has well defined protocol for "core" and gui communication. An example would be sancho, quite decent desktop client for mldonkey. Consider to implement that protocol and etorrent will have good desktop gui for free.

**Comment by jlouis** [comment]
Nice idea! I've deliberately kept the current GUI-stuff simple so people with a knack and want to hack GUIs in Erlang could do it. But an mldonkey gui frontend is most welcome as a part of this idea.

There are some code path merging which would be clever to make first though as the CLI and WebUI GUI does not share the same code path :/

**Comment by edwardw** [comment]
Yes, the first baby step could be to refactor CLI and WebUI GUI code, mainly `etorrent:list` and `etorrent_webui:list_torrents`. Those two should be able to share same code path.

**Comment by jlouis** [comment]
This is not going to happen in the near future anyway. MLdonkey is a pretty archaic program and I'll rather build a new web interface on top of cowboy than trying to retrofit the old MLdonkey GUI protocol to match.
