### ISSUE TITLE
Add support for eDonkey protocol

### ISSUE THREAD

**Issue by edwardw** [jlouis/etorrent#95]
Also known as ED2K. Not sure how difficult that might be. ED2K is very popular here in China and support it could gain etorrent some momentum.

Architecturally, this is also a fun challenge to make etorrent multi-protocol.

**Comment by jlouis** [comment]
If we want to pursue it, I think it is best to make a separate application (mind you, not repository). The reason is that there is little one can reuse as far as I remember from BitTorrent on the ED2K protocol. I don't think it is a simple task either :)

**Comment by jlouis** [comment]
Ok, getting away with this. We can't really solve it now, nor do I want to solve it.
